// simple.cpp generated by reflex 3.3.2 from simple.lxx

#define REFLEX_VERSION "3.3.2"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_bison               true
#define REFLEX_OPTION_flex                true
#define REFLEX_OPTION_lex                 yylex
#define REFLEX_OPTION_lexer               yyFlexLexer
#define REFLEX_OPTION_noyywrap            true
#define REFLEX_OPTION_outfile             "simple.cpp"
#define REFLEX_OPTION_prefix              yy
#define REFLEX_OPTION_yy                  true

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  FLEX-COMPATIBLE DEFINITIONS                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define INITIAL (0)
#define YY_NUM_RULES (5)

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  FLEX-COMPATIBLE ABSTRACT LEXER CLASS                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/flexlexer.h>
typedef reflex::FlexLexer<reflex::Matcher> FlexLexer;
#undef yyin
#undef yyout
#undef yytext
#undef yyleng
#undef yylineno

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

class yyFlexLexer : public FlexLexer {
 public:
  yyFlexLexer(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, NULL means std::cout by default
      std::ostream *os = NULL)
    :
      FlexLexer(input, os)
  {
  }
  // the flex lexer function defined by SECTION 2
  virtual int yylex(void);
  // lexer functions accepting new input to scan
  int yylex(const reflex::Input& input)
  {
    in(input);
    return yylex();
  }
  int yylex(const reflex::Input& input, std::ostream *os)
  {
    in(input);
    if (os)
      out(*os);
    return yylex();
  }
};

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %{ user code %}                                                //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 3 "simple.lxx"

#include <iostream>
#include <memory>
#include <string>

extern "C" int yylex();
extern "C" int yyerror(const char* s);

struct Node {
    std::string value;
    std::unique_ptr<Node> left, right;
};

void parse(Node &node);


////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  BISON                                                                     //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

yyFlexLexer YY_SCANNER;

#ifndef YY_EXTERN_C
#define YY_EXTERN_C
#endif

FILE *yyin = stdin;
FILE *yyout = stdout;

char *yytext;
yy_size_t yyleng;
int yylineno;

YY_EXTERN_C int yylex(void)
{
  if (yyin != YY_SCANNER.in())
    YY_SCANNER.in(yyin);  int yylex_token = YY_SCANNER.yylex();
  yytext = const_cast<char*>(YY_SCANNER.YYText());
  yyleng = static_cast<yy_size_t>(YY_SCANNER.YYLeng());
  yylineno = static_cast<int>(YY_SCANNER.lineno());
  return yylex_token;
}

#define yytext const_cast<char*>(YY_SCANNER.YYText())
#define yyleng static_cast<yy_size_t>(YY_SCANNER.YYLeng())
#define yylineno static_cast<int>(YY_SCANNER.lineno())

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

int yyFlexLexer::yylex(void)
{
  static const char *REGEX_INITIAL = "(?m)((?:[0-9])+)|((?:[*+\\x2d]))|([\\x09\\x20])|(.)|(\\n)";
  static const reflex::Pattern PATTERN_INITIAL(REGEX_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
    YY_USER_INIT
  }
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              yyterminate();
            }
            else
            {
              output(matcher().input());
            }
            YY_BREAK
          case 1: // rule simple.lxx:24: {DIGIT}+ :
            YY_USER_ACTION
#line 24 "simple.lxx"
{ std::cout << "integer: " << yytext << std::endl; }
            YY_BREAK
          case 2: // rule simple.lxx:25: {OPERATOR} :
            YY_USER_ACTION
#line 25 "simple.lxx"
{ std::cout << "operator: " << yytext << std::endl; }
            YY_BREAK
          case 3: // rule simple.lxx:26: [ \t] :
            YY_USER_ACTION
#line 26 "simple.lxx"
; // skip whitespace
            YY_BREAK
          case 4: // rule simple.lxx:27: . :
            YY_USER_ACTION
#line 27 "simple.lxx"
{ std::cerr << "unexpected character: " << yytext << std::endl; }
            YY_BREAK
          case 5: // rule simple.lxx:28: \n :
            YY_USER_ACTION
#line 28 "simple.lxx"
{ std::cout << "Enter a new expression: "; yylex(); }

            YY_BREAK
        }
  }
}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 3: user code                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#line 31 "simple.lxx"

void parse(Node &node) {
    std::string token;
    std::cin >> token;

    if (std::isdigit(token[0])) {
        node.value = token;
        return;
    }

    node.value = token;
    node.left = std::make_unique<Node>();
    parse(*node.left);
    node.right = std::make_unique<Node>();
    parse(*node.right);
}

int main() {
    std::cout << "Enter an expression: ";
    yylex();
    return 0;
}

int yyerror(const char* s) {
    std::cerr << "error: " << s << std::endl;
    return 0;
}
